@echo off
echo Starting SAMGA Website...
cd %~dp0
echo Installing dependencies...
call npm install
echo Checking environment file...
if not exist .env (
    echo Creating .env file from example...
    copy .env.example .env
)
echo Starting development server...
cmd /k npm run dev 